// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaHeQv3cFMptBd82ivBpRYkE9hymcGkIs',
    appId: '1:427751402464:web:9cd1a37906f2fd0435d985',
    messagingSenderId: '427751402464',
    projectId: 'flutter-bloc-phone-auth',
    authDomain: 'flutter-bloc-phone-auth.firebaseapp.com',
    storageBucket: 'flutter-bloc-phone-auth.appspot.com',
    measurementId: 'G-1RGL2CHTH0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvw8fWCeztB9Ykz7MZSCYwAXGztscDUWQ',
    appId: '1:427751402464:android:16c486c26a6c5efc35d985',
    messagingSenderId: '427751402464',
    projectId: 'flutter-bloc-phone-auth',
    storageBucket: 'flutter-bloc-phone-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpNF0BaquN-snxIsj7POFlkScfJzou8pQ',
    appId: '1:427751402464:ios:23a706cd780993a435d985',
    messagingSenderId: '427751402464',
    projectId: 'flutter-bloc-phone-auth',
    storageBucket: 'flutter-bloc-phone-auth.appspot.com',
    iosBundleId: 'com.example.flutterBlocPhoneAuthFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpNF0BaquN-snxIsj7POFlkScfJzou8pQ',
    appId: '1:427751402464:ios:8906e03625b2f8be35d985',
    messagingSenderId: '427751402464',
    projectId: 'flutter-bloc-phone-auth',
    storageBucket: 'flutter-bloc-phone-auth.appspot.com',
    iosBundleId: 'com.example.flutterBlocPhoneAuthFirebase.RunnerTests',
  );
}
